### ISSUE TITLE
Add real persistence for payment status

### ISSUE THREAD

**Issue by exarkun** [PrivateStorageio/PaymentServer#23]
`PaymentServer.Persistence` exposes a type class for persistence but it only implements it for an in-memory type.

Add persistence which outlives the PaymentServer process.  It would be cool if this were Tahoe-LAFS hosted for security and redundancy but it is probably more practical to keep a local SQLite3 database, talk to a SQL server someone else is managing, or use a plain text file or directory of text files.

**Comment by exarkun** [comment]
Local SQLite3 almost certainly makes the most sense for now.

**Comment by vu3rdd** [comment]
Since vouchers are created only after it is paid for,  I was thinking of having two tables:
1. a `vouchers` table with schema `(id INTEGER PRIMARY KEY, name TEXT)` that contains all the paid vouchers, redeemed or not.
2. a `redeemed` vouchers table with schema `(id INTEGER PRIMARY KEY, voucher_id INTEGER, fingerprint TEXT)`

To get a set of all the vouchers that has been paid but not redeemed, we can do a
`select distinct name from vouchers;`

If it is paid but not redeemed, we can do an `insert item` of the voucher id and the corresponding fingerprint into the second table.

Does this high level idea look okay?

**Comment by exarkun** [comment]
> a vouchers table with schema (id INTEGER PRIMARY KEY, name TEXT) that contains all the paid vouchers, redeemed or not.

The `name` field should perhaps also be unique.  It would be meaningless (or the meaning would be confusing) to have two rows with the same voucher in them, right?

> a redeemed vouchers table with schema (id INTEGER PRIMARY KEY, voucher_id INTEGER, fingerprint TEXT)

SQLite3 can enforce foreign key constraints so it might make sense to also give voucher_id a foreign key constraint on `vouchers.id`.

> To get a set of all the vouchers that has been paid but not redeemed, we can do a
select distinct name from vouchers;

This needs a join on `redeemed` right?  Since `vouchers` will contain *all* of them.  So something like `select distinct name from vouchers where vouchers.id != redeemed.voucher_id` would give you all of the vouchers that are paid and unredeemed.  Although we don't actually ever need all of them, I think.  So perhaps instead `select 1 from vouchers where vouchers.name = ? and vouchers.id != redeemed.voucher_id` (actually it's been a long time since I wrote very much SQL, I hope these suggestions aren't total nonsense).  Then you also need some behavior for the retry-redemption case.  Something like `select fingerprint from redeemed where voucher_id = vouchers.id and vouchers.text = ?` and then some fingerprint comparison in the Haskell code?

**Comment by exarkun** [comment]
Fixed by #26
