### ISSUE TITLE
Metrics identifiers must use only lowercase letters

### ISSUE THREAD

**Issue by hacklschorsch** [PrivateStorageio/PaymentServer#81]
It seems [Prometheus from 2.4.0 on refuses to scrape metrics with a capital letter in them](https://github.com/prometheus/prometheus/issues/4602).

This blocks https://whetstone.privatestorage.io/privatestorage/PrivateStorageio/-/merge_requests/92.

To do: Change all metrics identifiers to lowercase-only (`GET` to `get`, `POST` to `post`...)

**Comment by exarkun** [comment]
The metrics identifiers are currently generated automatically by the servant-prometheus library.  That library seems fairly inactive.  I'm not sure what the best course of action is here.

We could:
* Try to push fixes upstream and get them released then pull the new release into our stack resolver
* Fork the project, get the fixes there, release that, pull that project into our stack resolver
* Push the fixes somewhere and pull a git rev into our stack resolver (instead of a release)
* Find a different prometheus "client" library that works and switch to that
* Stop relying on a library at all and just manually track and emit the metrics
* ???
*

**Comment by hacklschorsch** [comment]
- finding a different library sounds like a good way to go?
- if that fails, I would kludge my way around this: curl the metrics endpoint, pipe it through a unix filter lowercasing the whole thing, write it to disk and scrape using the node_exporter textfile_collector
  - or write a lowercasing proxy even.

**Comment by hacklschorsch** [comment]
We already [use our own forked version](https://github.com/PrivateStorageio/PaymentServer/blob/e158f5b894e73ac28f3268f458473c9f002019b6/nix/servant-prometheus.nix#L108). Can we just add a `toLower` [somewhere around here](https://github.com/PrivateStorageio/servant-prometheus/blob/master/lib/Servant/Prometheus.hs#L149) and call it a day?

**Comment by exarkun** [comment]
Ha.  I forgot we forked that.  Hooray, forking.  Yes, seems like it should be pretty straightforward to land a fix in our fork, then.  Not sure if that is the right place but it looks plausible ... feel free to give it a shot, if you like, or I can try to take a closer look tomorrow.

**Comment by hacklschorsch** [comment]
I really know too little to about Haskell to do this in a reasonable timeframe :( Soon, hopefully.

I have created issue #86 for this.

**Comment by hacklschorsch** [comment]
Wait. This is already an issue. Well. I guess they are very related then.

Or better yet: #86 supersedes this issue since it has more info.
